### PR TITLE
Issue 4 create basic gameplay mechanics in game scene

### LINKED ISSUE #4: Create basic gameplay mechanics in GameScene
Create a scene for basic gameplay:
 - display game UUID in a label
 - a text label with the game state
 - a text label with game history
 - picker with all bet actions (text)
 - a "Bet" button
 - a "Check" button
 - background asset

Use `Game` model and make API calls to the [`/v1/games/*`](https://github.com/Blef-team/blef_game_engine/tree/develop/api) endpoints.

### PR DESCRIPTION
**Pull request by adrian-golian**
Closes #4

### CODE REVIEW

**Comment by maciej-pomykala** [comment]
Can you confirm that `"author" : "xcode"` in line 20 of 
- `Blef/Assets.xcassets/background-blur2.imageset/Contents.json`, 
- `Blef/Assets.xcassets/background-raw.imageset/Contents.json`, and
- `Blef/Assets.xcassets/empty.imageset/Contents.json`
and line 3 of `Blef/Assets.xcassets/Contents.json` is fine?

**Comment by maciej-pomykala** [comment]
Line 52 of `Blef/Utilities.swift` suggests game may be started if there are at least two players. What is the behaviour of the app if there are more than 8 players and, in line with the workings of the game engine, the engine will refuse to start the game?

**Comment by adrian-golian** [comment]
> Line 52 of `Blef/Utilities.swift` suggests game may be started if there are at least two players. What is the behaviour of the app if there are more than 8 players and, in line with our design, the engine will refuse to start the game?

To clarify - the checks on the client side (the app, in this case) are just for the app. If I don't check for at least 2 players, then the app will ask the game engine to start the game with just one player ...and the game engine will promptly tell the app that it won't do that. So the purpose of this check is not to protect the game engine from bad requests, it's to protect the app from having to deal with "400 Bad request" responses from the game engine API. Rather than display "Something went wrong" on the screen, we're preventing the user from ever tapping the "Start game" button in the first place.
Now, _if_ there were more 8 players in the game then why should it be the app's responsibility to stop someone from starting the game. The app just asks the GA API service for the game state and if the service is telling it that there are 10 players, then there are 10 players.

**Comment by adrian-golian** [comment]
> Can you confirm that `"author" : "xcode"` in line 20 of
> 
> * `Blef/Assets.xcassets/background-blur2.imageset/Contents.json`,
> * `Blef/Assets.xcassets/background-raw.imageset/Contents.json`, and
> * `Blef/Assets.xcassets/empty.imageset/Contents.json`
>   and line 3 of `Blef/Assets.xcassets/Contents.json` is fine?

Hm, I guess Xcode just does that, when you drag and drop some pictures/assets into it. I don't mind. I don't think we'll lose ownership of the assets this way (there's info in the licence file).

**Comment by maciej-pomykala** [comment]
My bad, the rule which prevents an eighth player joining is implemented in the 'join' endpoint of the engine and therefore the app doesn't need to check for this when starting a game.

**Pull request merged**
